### ISSUE TITLE
Support for Grammar Flow Graphs.

### ISSUE THREAD

**Issue by modulovalue** [mdaines/grammophone#27]
Hello @mdaines,

I've recently come across [A Graphical Model for Context-Free Grammar Parsing](https://rd.springer.com/content/pdf/10.1007/978-3-662-46663-6_1.pdf). It establishes a connection between control flow graphs and context free grammars. It calls them Grammar Flow Graphs (GFGs):

<img width="684" alt="Bildschirm­foto 2023-03-30 um 17 50 14" src="https://user-images.githubusercontent.com/24444584/228893843-712fe550-d89c-408f-b3c2-d7cf261b3e03.png">

I'm going to try to see how well graphviz can handle displaying them for my own tools. I think it would be really cool if grammophone supported them. If you'd consider doing that, I can share some of my experiments here.

**Comment by mdaines** [comment]
It seems interesting, although I'd need to give the paper a closer look to really say. The current feature set is based on Louden's _Compiler Construction: Principles and Practice_ which was the textbook in the course Grammophone was developed to supplement. If this type of diagram is used in other textbooks or courses, maybe it's a good candidate for a feature to add. Otherwise, I'm not sure I want to support it.

If you'd like to generate this type of diagram in your own tools, it could be helpful if the [`Grammar`](https://github.com/mdaines/grammophone/tree/v2/src/grammar) class was available in a separate package, which is something I've been thinking about doing.

**Comment by modulovalue** [comment]
> [...] I'm not sure I want to support it.

No problem, thank you for the response!

I have implemented a CFG to GFG to graphviz converter and here's how graphviz handles GFGs:

<img width="1300" alt="Bildschirm­foto 2023-03-31 um 21 25 56" src="https://user-images.githubusercontent.com/24444584/229211421-eb5fa0b7-9111-4ba9-b952-e05269e616ca.png">

not well, I think. Increasing the rank separation doesn't help much.

Given the goals of grammophone that you've mentioned, and the fact that graphviz doesn't seem to be well suited for visualizing such flow graphs, I am going to close this issue.
